"""group_id changed in user model

Revision ID: 1ffef33cd4c2
Revises: 13ac2c30f069
Create Date: 2024-07-19 18:31:10.684930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import apps.webui.internal.db


# revision identifiers, used by Alembic.
revision: str = '1ffef33cd4c2'
down_revision: Union[str, None] = '13ac2c30f069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migratehistory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migratehistory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('migrated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
